advanced/adv_app/urls.py
from django.urls import path
from adv_app import views

#template tagging
app_name = 'adv_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
]

advanced/advanced/urls.py
from django.contrib import admin
from django.urls import path,include
from adv_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('adv_app/',include('adv_app.urls',namespace='adv_app')),
]

advanced/adv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("adv_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete='Cascade')

    def __str__(self):
        return self.name

advanced/adv_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View,TemplateView,
                                    ListView,DetailView,
                                    CreateView,UpdateView,
                                    DeleteView)
from adv_app import models
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'adv_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("adv_app:list")

advanced/adv_app/templates/adv_app/app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <ul class="nav navbar-nav">
        <li> <a class="navbar-brand" href="{% url 'adv_app:list'%}">School</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
        <li><a href="#"></a></li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>

  </body>
</html>

advanced/adv_app/templates/adv_app/school_confirm_delete.html
{% extends 'adv_app/app_base.html' %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'adv_app:detail' pk=school.pk %}">Cancel</a>

</form>


{% endblock %}

advanced/adv_app/templates/adv_app/school_detail.html
{% extends 'adv_app/app_base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
      <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}

</div>

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'adv_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

advanced/adv_app/templates/adv_app/school_form.html
{% extends "adv_app/app_base.html"%}

{% block body_block %}

<h1>
   {% if not form.instance.pk %}
   Create School
   {% else %}
   Update School
   {% endif %}
</h1>

 <form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" class="btn btn-primary" value="Submit">

 </form>
 
{% endblock %}

advanced/adv_app/templates/adv_app/school_list.html
{% extends "adv_app/app_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools</h1>
  <ol>
    {% for school in schools %}
      <h2><li> <a href="{{school.id}}">{{school.name}}</a></li> </h2>
    {% endfor %}
  </ol>

{% endblock %}

advanced/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <ul class="nav navbar-nav">
        <li> <a class="navbar-brand" href="{% url 'adv_app:list'%}">School</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
        <li><a href="#"></a></li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>

  </body>
</html>

advanced/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page!</h1>
  </div>
{% endblock %}